# HW 4

Building a neural network using backpropagation.

In [128]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder
from sklearn import metrics
import pydotplus
from sklearn.model_selection import train_test_split

## Step 1:
Use the "titanic" dataset in homework 3

In [105]:
#Reading in Data
df = pd.read_csv('Titanic.csv')
df.head()

,Unnamed: 0,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
0,1,1st,1,"Allen, Miss. Elisabeth Walton",female,29.0000,0,0,24160,211.337494,B5,Southampton,2,NaN,"St Louis, MO"
1,2,1st,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,151.550003,C22 C26,Southampton,11,NaN,"Montreal, PQ / Chesterville, ON"
2,3,1st,0,"Allison, Miss. Helen Loraine",female,2.0000,1,2,113781,151.550003,C22 C26,Southampton,NaN,NaN,"Montreal, PQ / Chesterville, ON"
3,4,1st,0,"Allison, Mr. Hudson Joshua Crei",male,30.0000,1,2,113781,151.550003,C22 C26,Southampton,NaN,135.0,"Montreal, PQ / Chesterville, ON"
4,5,1st,0,"Allison, Mrs. Hudson J C (Bessi",female,25.0000,1,2,113781,151.550003,C22 C26,Southampton,NaN,NaN,"Montreal, PQ / Chesterville, ON"

In [107]:
#Dropping unnecessary columns
df.drop(df.columns[[0, 3, 7, 8, 9, 10, 11, 12, 13, 14]], axis=1, inplace=True)

## Step 2:
Fit a neural network using independent variables ‘pclass + sex + age + sibsp’ and dependent variable ‘survived’. Fill in n/a attributes with the average of the same attributes from other training examples.

In [108]:
#Fill Data with averages using fillna
#Used numeric_only=True to only apply code to columns/rows with numerical values
df.fillna(value=df.mean(numeric_only=True))

     pclass  survived     sex        age  sibsp
0       1st         1  female  29.000000      0
1       1st         1    male   0.916700      1
2       1st         0  female   2.000000      1
3       1st         0    male  30.000000      1
4       1st         0  female  25.000000      1
...     ...       ...     ...        ...    ...
1304    3rd         0  female  14.500000      1
1305    3rd         0  female  29.881135      1
1306    3rd         0    male  26.500000      0
1307    3rd         0    male  27.000000      0
1308    3rd         0    male  29.000000      0

[1309 rows x 5 columns]

In [95]:
features = ['pclass', 'sex', 'age', 'sibsp']
X = df[features].apply(LabelEncoder().fit_transform) 
y = df['survived']

print(X)
print(y)

      pclass  sex  age  sibsp
0          0    0   44      0
1          0    1    6      1
2          0    0    8      1
3          0    1   45      1
4          0    0   38      1
...      ...  ...  ...    ...
1304       2    0   22      1
1305       2    0   98      1
1306       2    1   40      0
1307       2    1   41      0
1308       2    1   44      0

[1309 rows x 4 columns]
0       1
1       1
2       0
3       0
4       0
       ..
1304    0
1305    0
1306    0
1307    0
1308    0
Name: survived, Length: 1309, dtype: int64

In [96]:
#Loading additional libraries & Modules
from sklearn.neural_network import MLPClassifier
from sklearn.neural_network import MLPRegressor
from sklearn.metrics import mean_squared_error
from math import sqrt
from sklearn.metrics import r2_score

In [97]:
print(df.shape)

(1309, 5)

In [98]:
df.describe().transpose()

           count       mean        std     min   25%   50%   75%   max
survived  1309.0   0.381971   0.486055  0.0000   0.0   0.0   1.0   1.0
age       1046.0  29.881135  14.413500  0.1667  21.0  28.0  39.0  80.0
sibsp     1309.0   0.498854   1.041658  0.0000   0.0   0.0   1.0   8.0

The mean value for survived is 0.38, meaning that ~38% survived. Therefore, the baseline accuracy is 62%, which our neural network model should exceed.

In [109]:
#Training the data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)
print(X_train.shape)
print(X_test.shape)

(1047, 4)
(262, 4)

Use 2 hidden layers and set the activation functions for both the hidden and output layer to be the sigmoid ('logistic') function. Set “solver” parameter as either SGD (stochastic gradient descend) or Adam (similar to SGD but optimized performance with mini batches). You can adjust parameter “alpha” for regularization (to control overfitting) and other parameters such as “learning rate” and “momentum” as needed

In [100]:
#Building, Predicting, and Evaluating the Neural Network Model
from sklearn.neural_network import MLPClassifier

mlp = MLPClassifier(hidden_layer_sizes=(16, 8), activation='logistic', solver='adam', alpha=1e-5, momentum=0.1, max_iter=300, verbose=True)
mlp.fit(X_train, y_train)

predict_train = mlp.predict(X_train)
predict_test = mlp.predict(X_test)

Iteration 1, loss = 0.67330637
Iteration 2, loss = 0.66888164
Iteration 3, loss = 0.66509593
Iteration 4, loss = 0.66225771
Iteration 5, loss = 0.65969335
Iteration 6, loss = 0.65818441
Iteration 7, loss = 0.65693469
Iteration 8, loss = 0.65611087
Iteration 9, loss = 0.65557939
Iteration 10, loss = 0.65504521
Iteration 11, loss = 0.65462992
Iteration 12, loss = 0.65432276
Iteration 13, loss = 0.65393054
Iteration 14, loss = 0.65362638
Iteration 15, loss = 0.65329257
Iteration 16, loss = 0.65297299
Iteration 17, loss = 0.65263723
Iteration 18, loss = 0.65237858
Iteration 19, loss = 0.65203305
Iteration 20, loss = 0.65168642
Iteration 21, loss = 0.65128017
Iteration 22, loss = 0.65088173
Iteration 23, loss = 0.65049498
Iteration 24, loss = 0.65011345
Iteration 25, loss = 0.64962667
Iteration 26, loss = 0.64916601
Iteration 27, loss = 0.64865089
Iteration 28, loss = 0.64827838
Iteration 29, loss = 0.64771617
Iteration 30, loss = 0.64692223
Iteration 31, loss = 0.64623821
Iteration 32, loss = 0.64540626
Iteration 33, loss = 0.64456414
Iteration 34, loss = 0.64368277
Iteration 35, loss = 0.64280152
Iteration 36, loss = 0.64174163
Iteration 37, loss = 0.64078209
Iteration 38, loss = 0.63964582
Iteration 39, loss = 0.63871649
Iteration 40, loss = 0.63730784
Iteration 41, loss = 0.63574696
Iteration 42, loss = 0.63475343
Iteration 43, loss = 0.63353914
Iteration 44, loss = 0.63147146
Iteration 45, loss = 0.62981449
Iteration 46, loss = 0.62853974
Iteration 47, loss = 0.62590354
Iteration 48, loss = 0.62458377
Iteration 49, loss = 0.62272187
Iteration 50, loss = 0.62025217
Iteration 51, loss = 0.61829599
Iteration 52, loss = 0.61670304
Iteration 53, loss = 0.61444924
Iteration 54, loss = 0.61144349
Iteration 55, loss = 0.61019655
Iteration 56, loss = 0.60797228
Iteration 57, loss = 0.60491395
Iteration 58, loss = 0.60316836
Iteration 59, loss = 0.60080391
Iteration 60, loss = 0.59823491
Iteration 61, loss = 0.59513650
Iteration 62, loss = 0.59335916
Iteration 63, loss = 0.59037462
Iteration 64, loss = 0.58778655
Iteration 65, loss = 0.58502382
Iteration 66, loss = 0.58224549
Iteration 67, loss = 0.58031341
Iteration 68, loss = 0.57776158
Iteration 69, loss = 0.57587233
Iteration 70, loss = 0.57195353
Iteration 71, loss = 0.56968459
Iteration 72, loss = 0.56657963
Iteration 73, loss = 0.56394324
Iteration 74, loss = 0.56263582
Iteration 75, loss = 0.55857384
Iteration 76, loss = 0.55811123
Iteration 77, loss = 0.55486386
Iteration 78, loss = 0.55174623
Iteration 79, loss = 0.54872565
Iteration 80, loss = 0.54624807
Iteration 81, loss = 0.54321487
Iteration 82, loss = 0.54244740
Iteration 83, loss = 0.53957796
Iteration 84, loss = 0.53670385
Iteration 85, loss = 0.53389517
Iteration 86, loss = 0.53200447
Iteration 87, loss = 0.52912923
Iteration 88, loss = 0.52680303
Iteration 89, loss = 0.52446987
Iteration 90, loss = 0.52205958
Iteration 91, loss = 0.51987238
Iteration 92, loss = 0.51867875
Iteration 93, loss = 0.51563149
Iteration 94, loss = 0.51371658
Iteration 95, loss = 0.51152153
Iteration 96, loss = 0.51098147
Iteration 97, loss = 0.50876885
Iteration 98, loss = 0.50583403
Iteration 99, loss = 0.50413912
Iteration 100, loss = 0.50214369
Iteration 101, loss = 0.50093951
Iteration 102, loss = 0.49837177
Iteration 103, loss = 0.49640473
Iteration 104, loss = 0.49529909
Iteration 105, loss = 0.49337822
Iteration 106, loss = 0.49348325
Iteration 107, loss = 0.49033420
Iteration 108, loss = 0.48873158
Iteration 109, loss = 0.48737424
Iteration 110, loss = 0.48616590
Iteration 111, loss = 0.48510036
Iteration 112, loss = 0.48401337
Iteration 113, loss = 0.48184063
Iteration 114, loss = 0.48065704
Iteration 115, loss = 0.47978860
Iteration 116, loss = 0.47875803
Iteration 117, loss = 0.47744953
Iteration 118, loss = 0.47608594
Iteration 119, loss = 0.47470284
Iteration 120, loss = 0.47587922
Iteration 121, loss = 0.47255085
Iteration 122, loss = 0.47295087
Iteration 123, loss = 0.47345532
Iteration 124, loss = 0.47087203
Iteration 125, loss = 0.46953684
Iteration 126, loss = 0.46927001
Iteration 127, loss = 0.46841894
Iteration 128, loss = 0.46743346
Iteration 129, loss = 0.46655830
Iteration 130, loss = 0.46593944
Iteration 131, loss = 0.46542644
Iteration 132, loss = 0.46465656
Iteration 133, loss = 0.46470644
Iteration 134, loss = 0.46423280
Iteration 135, loss = 0.46334497
Iteration 136, loss = 0.46444342
Iteration 137, loss = 0.46303840
Iteration 138, loss = 0.46213611
Iteration 139, loss = 0.46130892
Iteration 140, loss = 0.46207235
Iteration 141, loss = 0.46042648
Iteration 142, loss = 0.46190813
Iteration 143, loss = 0.46078294
Iteration 144, loss = 0.45959186
Iteration 145, loss = 0.46074060
Iteration 146, loss = 0.45987243
Iteration 147, loss = 0.45913090
Iteration 148, loss = 0.45940886
Iteration 149, loss = 0.46055078
Iteration 150, loss = 0.45708095
Iteration 151, loss = 0.45746748
Iteration 152, loss = 0.45661830
Iteration 153, loss = 0.45688563
Iteration 154, loss = 0.45625221
Iteration 155, loss = 0.45584082
Iteration 156, loss = 0.45558064
Iteration 157, loss = 0.45598623
Iteration 158, loss = 0.45479602
Iteration 159, loss = 0.45432260
Iteration 160, loss = 0.45476580
Iteration 161, loss = 0.45384534
Iteration 162, loss = 0.45398782
Iteration 163, loss = 0.45375569
Iteration 164, loss = 0.45343985
Iteration 165, loss = 0.45306520
Iteration 166, loss = 0.45316308
Iteration 167, loss = 0.45329287
Iteration 168, loss = 0.45271958
Iteration 169, loss = 0.45247140
Iteration 170, loss = 0.45299423
Iteration 171, loss = 0.45342552
Iteration 172, loss = 0.45260426
Iteration 173, loss = 0.45209030
Iteration 174, loss = 0.45153005
Iteration 175, loss = 0.45084836
Iteration 176, loss = 0.45162669
Iteration 177, loss = 0.45201678
Iteration 178, loss = 0.45017922
Iteration 179, loss = 0.45095346
Iteration 180, loss = 0.44972916
Iteration 181, loss = 0.45146474
Iteration 182, loss = 0.45099282
Iteration 183, loss = 0.45135147
Iteration 184, loss = 0.45339162
Iteration 185, loss = 0.44917376
Iteration 186, loss = 0.44945321
Iteration 187, loss = 0.44943317
Iteration 188, loss = 0.44964687
Iteration 189, loss = 0.44954614
Iteration 190, loss = 0.44856241
Iteration 191, loss = 0.44893614
Iteration 192, loss = 0.44816370
Iteration 193, loss = 0.44870441
Iteration 194, loss = 0.44862858
Iteration 195, loss = 0.44974947
Iteration 196, loss = 0.45018390
Iteration 197, loss = 0.44656301
Iteration 198, loss = 0.45032314
Iteration 199, loss = 0.44769710
Iteration 200, loss = 0.44795651
Iteration 201, loss = 0.44973971
Iteration 202, loss = 0.44777112
Iteration 203, loss = 0.44693510
Iteration 204, loss = 0.44724123
Iteration 205, loss = 0.44600945
Iteration 206, loss = 0.44658667
Iteration 207, loss = 0.44602826
Iteration 208, loss = 0.44694500
Iteration 209, loss = 0.44662040
Iteration 210, loss = 0.44661439
Iteration 211, loss = 0.44602305
Iteration 212, loss = 0.44608325
Iteration 213, loss = 0.44527307
Iteration 214, loss = 0.44573507
Iteration 215, loss = 0.44499538
Iteration 216, loss = 0.44465880
Iteration 217, loss = 0.44529800
Iteration 218, loss = 0.44582164
Iteration 219, loss = 0.44568666
Iteration 220, loss = 0.44527528
Iteration 221, loss = 0.44443799
Iteration 222, loss = 0.44519523
Iteration 223, loss = 0.44452617
Iteration 224, loss = 0.44544842
Iteration 225, loss = 0.44483388
Iteration 226, loss = 0.44357916
Iteration 227, loss = 0.44505390
Iteration 228, loss = 0.44334861
Iteration 229, loss = 0.44379512
Iteration 230, loss = 0.44337413
Iteration 231, loss = 0.44343629
Iteration 232, loss = 0.44266580
Iteration 233, loss = 0.44400487
Iteration 234, loss = 0.44300618
Iteration 235, loss = 0.44235564
Iteration 236, loss = 0.44292315
Iteration 237, loss = 0.44242997
Iteration 238, loss = 0.44264354
Iteration 239, loss = 0.44193933
Iteration 240, loss = 0.44170100
Iteration 241, loss = 0.44266682
Iteration 242, loss = 0.44282302
Iteration 243, loss = 0.44246043
Iteration 244, loss = 0.44134886
Iteration 245, loss = 0.44145454
Iteration 246, loss = 0.44137733
Iteration 247, loss = 0.44123770
Iteration 248, loss = 0.44143797
Iteration 249, loss = 0.44113960
Iteration 250, loss = 0.44132943
Iteration 251, loss = 0.44083870
Iteration 252, loss = 0.44229430
Iteration 253, loss = 0.44074551
Iteration 254, loss = 0.44084802
Iteration 255, loss = 0.44044161
Iteration 256, loss = 0.44125869
Iteration 257, loss = 0.44067012
Iteration 258, loss = 0.44264678
Iteration 259, loss = 0.44149216
Iteration 260, loss = 0.44003148
Iteration 261, loss = 0.44022107
Iteration 262, loss = 0.43925750
Iteration 263, loss = 0.43979931
Iteration 264, loss = 0.43982584
Iteration 265, loss = 0.43924429
Iteration 266, loss = 0.43909747
Iteration 267, loss = 0.43916311
Iteration 268, loss = 0.43890247
Iteration 269, loss = 0.43997370
Iteration 270, loss = 0.43909094
Iteration 271, loss = 0.44012013
Iteration 272, loss = 0.43909131
Iteration 273, loss = 0.43841525
Iteration 274, loss = 0.44112058
Iteration 275, loss = 0.43834982
Iteration 276, loss = 0.43870331
Iteration 277, loss = 0.43824652
Iteration 278, loss = 0.43837448
Iteration 279, loss = 0.43800311
Iteration 280, loss = 0.43796250
Iteration 281, loss = 0.43838042
Iteration 282, loss = 0.43768576
Iteration 283, loss = 0.43774057
Iteration 284, loss = 0.43896411
Iteration 285, loss = 0.43653242
Iteration 286, loss = 0.43983694
Iteration 287, loss = 0.43789459
Iteration 288, loss = 0.43939661
Iteration 289, loss = 0.43750059
Iteration 290, loss = 0.44027403
Iteration 291, loss = 0.43734424
Iteration 292, loss = 0.43790389
Iteration 293, loss = 0.43773168
Iteration 294, loss = 0.43701359
Iteration 295, loss = 0.43786198
Iteration 296, loss = 0.43624650

Iteration 297, loss = 0.43668036
Iteration 298, loss = 0.43670301
Iteration 299, loss = 0.43614649
Iteration 300, loss = 0.43612580

/Users/erinbrown/anaconda3/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py:684: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (300) reached and the optimization hasn't converged yet.
  warnings.warn(

In [143]:
from sklearn.metrics import classification_report,confusion_matrix
print(confusion_matrix(y_train,predict_train))
print(classification_report(y_train,predict_train))

[[615  50]
 [154 228]]
              precision    recall  f1-score   support

           0       0.80      0.92      0.86       665
           1       0.82      0.60      0.69       382

    accuracy                           0.81      1047
   macro avg       0.81      0.76      0.77      1047
weighted avg       0.81      0.81      0.80      1047

In [145]:
print(confusion_matrix(y_test,predict_test))
print(classification_report(y_test,predict_test))

[[131  13]
 [ 56  62]]
              precision    recall  f1-score   support

           0       0.70      0.91      0.79       144
           1       0.83      0.53      0.64       118

    accuracy                           0.74       262
   macro avg       0.76      0.72      0.72       262
weighted avg       0.76      0.74      0.72       262

## Step 3:
Check the performance of the model with out-of- sample accuracy, defined as;

out-of-sample percent survivors correctly predicted (on test set)

out-of-sample percent fatalities correctly predicted (on test set)

Please try two different network structures (i.e., number of neurons at each hidden layer) and show their respective accuracy

In [169]:
outofsamplesurvivors = 1 - sum(predict_test[y_test ==1]^y_test[y_test == 1])/len(y_test[y_test ==1])
outofsamplefatalities = 1 - sum(predict_test[y_test ==0]^y_test[y_test == 0])/len(y_test[y_test ==0])

print(f"Correctly Predicted Out-of-Sample percent Survivors: {outofsamplesurvivors*100:.2f}%")
print(f"Correctly Predicted Out-of-Sample percent Fatalities: {outofsamplefatalities*100:.2f}%")

Correctly Predicted Out-of-Sample percent Survivors: 52.54%
Correctly Predicted Out-of-Sample percent Fatalities: 90.97%

## Step 4:
Compare the out-of-sample accuracy (as defined in step 3) with the random forest obtained in homework 3. (You can either use a table or plot the results of the two algorithms in one figure). Explain any difference in accuracy

In [170]:
from tabulate import tabulate
table = [['MLP Accuracy', 'Random Forest Accuracy'],
         ['52.54% Survivors', '87.67% Survivors'],
         ['90.97% Fatality','71.43% Fatality']]
print(tabulate(table, headers='firstrow', tablefmt='grid'))

+------------------+--------------------------+
| MLP Accuracy     | Random Forest Accuracy   |
+==================+==========================+
| 52.54% Survivors | 87.67% Survivors         |
+------------------+--------------------------+
| 90.97% Fatality  | 71.43% Fatality          |
+------------------+--------------------------+

The out-of-sample accuracy for MLP is significantly lower for "Survivors" in comparison to the out-of-sample accuracy for the random forest. On the contrary, the out-of-sample accuracy for MLP is significantly higher for "Fatalities" than the out-of-sample accuracy for the Random Forest. 

However, because the difference in Survivors accuracy between MLP and Random Forest is 35.13% wth Rnadom Forest having higher accuracy, and the difference between Fatalities accuracy for MLP and Random Forest is 19.54% with MLP having the higher accuracy, I would conclude that Random Forest Accuracy is better overall considering the survivors accuracy for MLP is very low.